version: 2.1

orbs:
  orb-tools: circleci/orb-tools@12.0
  core: {}

filters: &filters
  tags:
    only: /.*/

release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  ensure-npm-version:
    executor: core/node
    steps:
      - core/ensure_pkg_manager:
          ref: npm@latest
      - run:
          name: Validate version
          command: |
            NPM_LATEST_VERSION=$(npm view npm version)
            if ! npm --version | grep -q "$NPM_LATEST_VERSION"; then
              echo "npm version $NPM_LATEST_VERSION not found"
              exit 1
            fi
  ensure-pnpm-version-node-16:
    executor:
      name: core/node
      tag: '16.20'
    steps:
      - core/ensure_pkg_manager:
          ref: pnpm@8.8.0
      - run:
          name: Validate version
          command: |
            if ! pnpm --version | grep -q "8.8.0"; then
              echo "pnpm version 8.8.0 not found"
              exit 1
            fi
  ensure-pnpm-version-node-18:
    executor:
      name: core/node
      tag: '18.19'
    steps:
      - core/ensure_pkg_manager:
          ref: pnpm@9.0.1
      - run:
          name: Validate version
          command: |
            if ! pnpm --version | grep -q "9.0.1"; then
              echo "pnpm version 9.0.1 not found"
              exit 1
            fi
  ensure-pnpm-latest:
    executor: core/node
    steps:
      - checkout
      - run: cd sample
      - core/ensure_pkg_manager:
          ref: pnpm
      - run:
          name: Validate version
          command: |
            PNPM_LATEST_VERSION=$(npm view pnpm version)
            if ! pnpm --version | grep -q "$PNPM_LATEST_VERSION"; then
              echo "pnpm version $PNPM_LATEST_VERSION not found"
              exit 1
            fi
  install-dependencies-npm-node-16:
    executor:
      name: core/node
      tag: '16.20'
    steps:
      - checkout
      - core/install_dependencies:
          pkg_manager: npm
          pkg_json_dir: ~/project/sample
          cache_version: node16_v7
      - run: cd ~/project/sample && npm run build
  install-dependencies-pnpm-node-16:
    executor:
      name: core/node
      tag: '16.20'
    steps:
      - checkout
      - core/install_dependencies:
          pkg_manager: pnpm@latest-8
          pkg_json_dir: ~/project/sample
          cache_version: node16_v7
      - run: cd ~/project/sample && pnpm run build
  install-dependencies-custom-command:
    executor: core/node
    steps:
      - checkout
      - core/install_dependencies:
          pkg_manager: npm
          pkg_json_dir: ~/project/sample
          install_command: npm install
          cache_version: v9
      - run: cd ~/project/sample && npm run build
  run-script-npm:
    executor: core/node
    steps:
      - core/run_script:
          pkg_manager: npm
          pkg_json_dir: ~/project/sample
          script: test -- --json --outputFile=results_npm.json
      - run:
          name: Print output file
          working_directory: ~/project/sample
          command: cat results_npm.json
  run-script-pnpm:
    executor: core/node
    steps:
      - core/run_script:
          pkg_manager: pnpm
          pkg_json_dir: ~/project/sample
          script: test --json --outputFile=results_pnpm.json
      - run:
          name: Print output file
          working_directory: ~/project/sample
          command: cat results_pnpm.json

workflows:
  test-deploy:
    jobs:
      - ensure-npm-version:
          filters: *filters
      - ensure-pnpm-version-node-16:
          filters: *filters
      - ensure-pnpm-version-node-18:
          filters: *filters
      - ensure-pnpm-latest:
          filters: *filters
      - install-dependencies-npm-node-16:
          filters: *filters
      - install-dependencies-pnpm-node-16:
          filters: *filters
      - install-dependencies-custom-command:
          filters: *filters
      - run-script-npm:
          filters: *filters
      - run-script-pnpm:
          filters: *filters
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: studion/core
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
            - ensure-npm-version
            - ensure-pnpm-version-node-16
            - ensure-pnpm-version-node-18
            - ensure-pnpm-latest
            - install-dependencies-npm-node-16
            - install-dependencies-pnpm-node-16
            - install-dependencies-custom-command
            - run-script-npm
            - run-script-pnpm
          context: orb-publishing
          filters: *release-filters
