version: 2.1

orbs:
  orb-tools: circleci/orb-tools@12.0
  core: {}

filters: &filters
  tags:
    only: /.*/

release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  install-dependencies-npm-node-16:
    executor:
      name: core/node
      tag: '16.20'
    steps:
      - checkout
      - core/install_dependencies:
          pkg_json_dir: ~/project/sample
          cache_version: node16_v7
      - run: cd ~/project/sample && npm run build
  install-dependencies-pnpm-node-16:
    executor:
      name: core/node
      tag: '16.20'
    steps:
      - checkout
      - core/install_dependencies:
          pkg_manager: pnpm
          pkg_json_dir: ~/project/sample
          cache_version: node16_v7
      - run: cd ~/project/sample && pnpm run build
  install-dependencies-custom-command:
    executor: core/node
    steps:
      - checkout
      - core/install_dependencies:
          pkg_json_dir: ~/project/sample
          install_command: npm install
          cache_version: v9
      - run: cd ~/project/sample && npm run build
  run-script-npm:
    executor: core/node
    steps:
      - core/run_script:
          pkg_json_dir: ~/project/sample
          script: test -- --json --outputFile=results_npm.json
      - run:
          name: Print output file
          working_directory: ~/project/sample
          command: cat results_npm.json
  run-script-pnpm:
    executor: core/node
    steps:
      - core/run_script:
          pkg_manager: pnpm
          pkg_json_dir: ~/project/sample
          script: test --json --outputFile=results_pnpm.json
      - run:
          name: Print output file
          working_directory: ~/project/sample
          command: cat results_pnpm.json

workflows:
  test-deploy:
    jobs:
      - install-dependencies-npm-node-16:
          filters: *filters
      - install-dependencies-pnpm-node-16:
          filters: *filters
      - install-dependencies-custom-command:
          filters: *filters
      - run-script-npm:
          filters: *filters
      - run-script-pnpm:
          filters: *filters
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: studion/core
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
            - install-dependencies-npm-node-16
            - install-dependencies-pnpm-node-16
            - install-dependencies-custom-command
            - run-script-npm
            - run-script-pnpm
          context: orb-publishing
          filters: *release-filters
